### PR TITLE
Updated Serialisation

### PR DESCRIPTION
**Pull request by sumo**
Made the following changes
- Improve actual API and separate into a new module
- Add mclwasm compatible serialisation

mclwasm de/serialisation has been tested for G1, G2, GT and Fr in the browser.

### CODE REVIEW

**Comment by sdiehl** [comment]
Thanks for the contribution. We'll take a look at this on Monday and make some comments. I don't see any reason we can't include this though.

**Review by Acentelles — APPROVED** [review]

**Comment by sdiehl** [comment]
@sumo Thanks for the PR. We're just running the final QA on this library and we'll get a patch version of it up to Hackage shortly.

**Comment by sdiehl** [comment]
This has landed on Hackage now. 
http://hackage.haskell.org/package/pairing

**Comment by sumo** [comment]
Thanks for letting me know. Glad I could contribute!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
